apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "mysql.fullname" .) }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: mysql
